nginx:
  name: nginx-proxy
  labels:
    id: C0929518
    app: wordpress
    env: dev
  image:
    repository: karkironisha/proxy
    tag: v1
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: NodePort
    port: 80
    targetPort: 80
